<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
	<ApplicationIcon>ico/app.ico</ApplicationIcon>
	<Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ClassFirewall</AssemblyName>
    <RootNamespace>ClassFirewall</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Product>Class Firewall</Product>
    <AssemblyTitle>Class Firewall</AssemblyTitle>

    <!-- ========== 单文件发布相关 ========== -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <!-- SelfContained=true：目标电脑无需预装 .NET 8 运行时 -->
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <!-- 压缩仅允许在 SelfContained=true 时使用，否则报 NETSDK1176 -->
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
    <!-- ================================== -->

  </PropertyGroup>

<ItemGroup>
  <EmbeddedResource Include="ico\app.ico" />
</ItemGroup>
</Project>